# Bu fayl Dart kodini statik tahlil qilishni sozlaydi, bu xatolar, ogohlantirishlar va lintlarni tekshiradi.
#
# Tahlilchi tomonidan aniqlangan masalalar Dart imkoniyatiga ega IDElarda (https://dart.dev/tools#ides-and-editors) UI orqali ko'rsatiladi.
# Tahlilchini buyruq satridan `flutter analyze` buyrug'ini bajarish orqali ham chaqirish mumkin.

# Flutter ilovalari, paketlari va plaginlar uchun tavsiya etilgan lintlarni faollashtiradi.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    prefer_const_constructors: ignore  # Constant konstruktorlarni afzal ko'rish qoidasi uchun xatolikni e'tiborsiz qoldiradi

linter:
  rules:
    # Ushbu loyihaga qo'llaniladigan lint qoidalari `package:flutter_lints/flutter.yaml` dan o'chirilishi yoki qo'shilishi mumkin.
    # Qoidalarning ro'yxati va ularning hujjatlari https://dart.dev/lints saytida chop etilgan.
    
    # `print` dan foydalanishni taqiqlash qoidasi
    # avoid_print: false  # 'print' qoidasi uchun e'tiborsiz qoldirish
    # Yakkalangan qo'shtirnoqlardan foydalanishni afzal ko'rish qoidasi
    # prefer_single_quotes: true  # Yakkalangan qo'shtirnoqlardan foydalanishni yoqish

# Ushbu fayl haqida qo'shimcha ma'lumotlarni quyida topishingiz mumkin:
# https://dart.dev/guides/language/analysis-options
